### ISSUE TITLE
tdslite works on ESP32, but need helps for displaying the queried data.

### ISSUE THREAD

**Issue by NodeMCU-Kang** [mustafakemalgilor/tdslite#4]
@mustafakemalgilor I tried tdslite on my ESP32 DeviKitC board, it works well. 

However, since I am a newbie for C++, I would need your helps. I used  tdslite/tests/sketches/esp/esp.cpp and modified to accommodate my WiFi SSID/PWD, SQL Server addres/username/password .... 

And changed setup() and loop() to have tdslite_loop() run only once.
```
// --------------------------------------------------------------------------------
void setup() {
    bool r = {false};
    r      = init_serial();
    r      = r && wifi_setup();
    r      = r && tdslite_setup();
    if (not r) {
        SERIAL_PRINTLNF("... setup failed ...");
        for (;;) {
            delay(1000);
        }
    }
    SERIAL_PRINTLNF("--- setup finished ---");

    tdslite_loop();
}

// --------------------------------------------------------------------------------

void loop() {
    // tdslite_loop();
    // delay(250);
}
```
The Serial output from ESP32 is as below
...
received COLMETADATA token -> column count [3]
row field 0 -> []
row field 1 -> []
row field 2 -> []
**row: 1  2       1701998412**
received done token -> status [16] | cur_cmd [193] | done_row_count [1]
cc: done token -- affected rows(1)
network_impl_base::do_receive_tds_pdu(...) -> packet_data_cb needs `0` more bytes
netbuf: [consumed `282`, inuse `0`, free `8192`]
netbuf: [consumed `0`, inuse `0`, free `8192`]
'>> Report: row count [1] <<

For the output of "**row: 1  2       1701998412**", I believe the third column is a pointer printed as uint32. I would like the output be like "**row:1 2 Lorem ipsum ...  velit.**".

I know I should modify the codes in row_callback(), but as a C++ newbie, I have no idea how to modify the codes
```
    for (const auto & field : row) {
        SERIAL_PRINTF("%d\t", field.as<tdsl::uint32_t>());
    }
```

Sorry for the C++ newbie question, your helps would be much appreciated.

**Comment by mustafakemalgilor** [comment]
Hello @NodeMCU-Kang 

You need to access the fields by index and cast them to their respective data type. Assume that you have a table like: `CREATE TABLE TEST(a int, b real, c varchar(50))`, you can use the following callback to display the rows:

```c++
static void row_callback(void * u, const tdsl::tds_colmetadata_token & colmd,
                         const tdsl::tdsl_row & row) {
    SERIAL_PRINTLNF("row: %d %f %s", row[0].as<int>(), row[1].as<float>(), row[2].as<tdsl::char_view>().data());
}
```

**Comment by NodeMCU-Kang** [comment]
Hi @mustafakemalgilor Thank you very much. The complier complained about "row[0].as\<int\>()" and "row[1].as\<float\>()". I changed them to int32_t then it works,
```
SERIAL_PRINTLNF("row: %d, %d, %s", row[0].as<tdsl::int32_t>(), row[1].as<tdsl::int32_t>(), row[2].as<tdsl::char_view>().data());
